#!/bin/bash



echo "clear..."
rm -rf "$1"
rm -rf "Thumb point $1"
rm -rf ./video_utovr/video/*
rm -rf ./video_utovr/[^index]*.html
echo "done"


######### how to use ###########

# execute ./clear.sh to delete all of files generated by executing ./main.sh
