#!/bin/bash

############## edit it ###############
files=( "video_utovr" "Thumb $1" "Thumb point $1" "$1" )


if [ ! -d "Backup $1" ]; then
	echo "ATTENTION: folder: Backup $1 doesn't exist"
	echo "Are you sure to continue? y/n:"
	read answer
	if [[ ! "$answer" =~ ^y.* && ! "$answer" =~ ^Y.* ]]; then
		echo "quit"
		exit 0
	fi
fi

if [ ! -d "Thumb $1" ]; then
	echo "ATTENTION: folder: Thumb $1 doesn't exist"
	echo "Are you sure to continue? y/n:"
	read answer
	if [[ ! "$answer" =~ ^y.* && ! "$answer" =~ ^Y.* ]]; then
		echo "quit"
		exit 0
	fi
fi

cd "`dirname "$0"`";

if [[ "$2" == "clean" || "$2" == "clear" ]]; then
	./clear.sh "$1"
	exit 0
fi

if [[ "$2" == "init" ]]; then
	./rmexe.sh

	echo "process krpano"
	./processKrpano.sh

	./clear.sh "$1"

	echo "generate new data"
	echo "This gonna take long time..."
	cp -r "Backup $1" "$1"
	echo "$1" "done"
	cp -r "Backup $1" "Thumb point $1"
	echo "Thumb point $1" "done"
	rm -rf ./video_utovr/video
	mkdir ./video_utovr/video
	cp -r "$1" ./video_utovr/video/
	cp -r "Thumb $1" ./video_utovr/video/
	echo "video $1" "done"

	echo "generate thumb point"
	find "Thumb point $1" -type f -name "*.mp3" -exec rm -rf {} \; 2>/dev/null
	find "Thumb point $1" -type f -name "*.mp4" -exec rm -rf {} \; 2>/dev/null
	find "Thumb point $1" -type d -name "vtour" -exec rm -rf {} \; 2>/dev/null

	echo "generate $1"
	find "$1" -type f -name "*.mp4" -exec rm -rf {} \; 2>/dev/null
	find "$1" -type f -name "Thumb*" -exec rm -rf {} \; 2>/dev/null

	echo "generate video"
	find video_utovr -type f -name "*.mp3" -exec rm -rf {} \; 2>/dev/null
	find video_utovr -type f -name "*.jpg" -exec rm -rf {} \; 2>/dev/null
	find video_utovr -type f ! -name 'Thumb*.mp4' rm -rf {} \; 2>/dev/null
	find video_utovr -type d -name "vtour" -exec rm -rf {} \; 2>/dev/null

	echo "generate html for video"
	./video_utovr/generateIndex.sh
fi

if [[ "$3" == "upload" || "$4" == "upload" ]]; then
	./upload.sh "$2" "${files[@]}"
fi



 ####### How to use ########

# dir
#  |----country
#  |----Thumb country
#  |----Thumb point country
#  |----video_utovr
#  |----upload.sh


# execute main.sh as below:
# ./main.sh country init  --- generate directories to upload
# ./main.sh country clean # clear  --- delete directories generated by init command
# ./main.sh country continent upload  --- upload generated directories to 7niu space whose name is continent
# ./main.sh country continent init upload  --- init + upload ---- ATTENTION: Not recommended!!! Because generated directories may be incorrect.

# You can manually edit the variable $files and execute ./main.sh country continent upload to update the space of 7niu.
