#!/bin/bash


echo "remove server of krpano"
find . -name "tour_testingserver.exe" -type f -delete
find . -name "tour_testingserver_macos" -type f -delete

find . -name "tour.swf" -type f -delete
find . -name "tour.js" -type f -delete
find . -name "skin" -type d -exec rm -rf {} +
find . -name "plugins" -type d -exec rm -rf {} +


####### How to use ########

# dir
#  |----subdir1
#  |----subdir2
#  |----upload.sh

# execute ./rmexe.sh to remove all of executable files generated by krpano to do local test

